version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: michigan_db2
    environment:
      POSTGRES_HOST: pg.pg4e.com
      POSTGRES_PORT: 5432
      POSTGRES_DB: pg4e_7f9be95220
      POSTGRES_USER: pg4e_7f9be95220
      POSTGRES_PASSWORD: pg4e_p_54ab84c35b12c2e
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./schemas:/docker-entrypoint-initdb.d

volumes:
  pg_data:

